deb822 / retab / stuff..

diff --git a/fnt b/fnt
--- a/fnt
+++ b/fnt
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-
+# vim autoindent noexpandtab
 set -e
 
 # APT but only for fonts
@@ -9,6 +9,7 @@ set -e
 
 #TMPDIR="${TMPDIR:-/tmp}"
 TMPDIR="${HOME}/.fnt"
+PACKAGES="${TMPDIR}/Packages.xz"
 # debian sid index
 #INDEX="http://ftp.ch.debian.org/debian/dists/sid/main/binary-all/Packages.xz"
 MIRROR="http://deb.debian.org/debian"
@@ -37,10 +38,10 @@ case "$s" in
 		i="apt"
 		md5="md5sum"
 		target="$HOME/.fonts/"
-    if [ 0 -eq "$(id -u)" ]; then
-        		target="/usr/local/share/fonts/"
+		if [ 0 -eq "$(id -u)" ]; then
+			target="/usr/local/share/fonts/"
 			mkdir -p $target
-    		fi
+		fi
 	;;
 	FreeBSD)
 		#echo FreeBSD
@@ -68,10 +69,10 @@ case "$s" in
 esac
 
 for a in $check; do
-    if ! command -v "$a" &>/dev/null; then
-        echo "$a not found, please use $i to install it."
-        exit 1
-    fi
+	if ! command -v "$a" &>/dev/null; then
+		echo "$a not found, please use $i to install it."
+		exit 1
+	fi
 done
 
 if [ -z "$1" ]; then
@@ -93,8 +94,8 @@ case "$1" in
 	update|-u)
 		echo Updating...
 		mkdir -p "${TMPDIR}"
-	        if [ -f "${TMPDIR}/Packages.xz" ]; then rm "${TMPDIR}/Packages.xz"; fi
-        	curl -s "$INDEX" -o "${TMPDIR}/Packages.xz"
+		if [ -f "${PACKAGES}" ]; then rm "${PACKAGES}"; fi
+		curl -s "$INDEX" -o "${PACKAGES}"
 	;;
 
 	info)
@@ -106,23 +107,30 @@ case "$1" in
 		# echo Listing...
 		# macOS mainly comes with *.ttc (truetype font collections, that can not be processed by otfinfo)
 		#ls -1 /System/Library/Fonts/*.?tf /usr/share/fonts/*type/*/*.?tf $HOME/Library/Fonts/*.?tf $HOME/.fonts/*.?tf 2>/dev/null | while read f; do
-		ls -1 "$HOME"/Library/Fonts/*.?tf "$HOME"/.fonts/*.?tf /usr/local/share/fonts/*.?tf 2>/dev/null | while read f; do
-			echo "$f" [$(otfinfo -u "$f" 2>/dev/null|wc -l|awk '{print $1}')] | sed s,.*/,,
+		find "${HOME}"/{Library,.fonts}/ /usr/local/share/fonts -iname '*.?tf' | while read -r f; do
+			echo "$(basename "${f}") [ $(otfinfo -u "$f" 2>/dev/null | wc -l) ]"
 		done
+		# ls -1 "$HOME"/Library/Fonts/*.?tf "$HOME"/.fonts/*.?tf /usr/local/share/fonts/*.?tf 2>/dev/null | while read f; do
+		# 	echo "$f" [ $(otfinfo -u "$f" 2>/dev/null | wc -l | awk '{print $1}') ] | sed s,.*/,,
+		# done
 	;;
 	preview|-p)
 		# echo Previewing...
 		mkdir -p "${TMPDIR}"
-		curl -L -s "https://screenshots.debian.net/screenshot/fonts-$2" -o "${TMPDIR}/preview.png"
-		md5s=$($md5 ${TMPDIR}/preview.png)
-                echo $md5s |grep b5765b390157e36eaf721c8848a4b04d >/dev/null &&
-                  curl -L -s "https://sid.ethz.ch/fonts/$2/preview.png" -o "${TMPDIR}/preview.png"
+		if curl -L -s "https://screenshots.debian.net/screenshot/fonts-$2" -o "${TMPDIR}/preview.png"; then
+			md5s=$($md5 "${TMPDIR}/preview.png")
+			if echo "$md5s" |grep b5765b390157e36eaf721c8848a4b04d >/dev/null; then
+				if curl -L -s "https://sid.ethz.ch/fonts/$2/preview.png" -o "${TMPDIR}/preview.png"; then
+					chafa -c 240 -w 9 -O 9 -p on --symbols all "${TMPDIR}/preview.png"
+				fi
+			fi
+		fi
 		#chafa --invert -c none --symbols block+border-solid "${TMPDIR}/preview.png"
 		chafa -c 240 -w 9 -O 9 -p on --symbols all "${TMPDIR}/preview.png"
 	;;
 	install|-i)
-		if [ ! -f "${TMPDIR}/Packages.xz" ]; then
-			echo "Could not find ${TMPDIR}/Packages.xz"
+		if [ ! -f "${PACKAGES}" ]; then
+			echo "Could not find ${PACKAGES}"
 			echo "Please run $0 update"
 			# could also just run itself with update...
 			exit 1
@@ -132,42 +140,45 @@ case "$1" in
 		fi
 		# cat $HOME/.fnt/Packages.xz |unxz|grep "^Package:\|^Homepage:\|^Size:\|^Installed-Size:\|^Description:"
 		# cat $HOME/.fnt/Packages.xz |unxz| awk '!NF{print line; line=""}{line=line " " $0}' |grep "Package: fonts-"
-		p=$(unxz -c "$HOME/.fnt/Packages.xz" | grep -v "^Architecture:\|^Section:\|^Priority:\|^Replaces:\|^Provides:\|^Brekas:\|^Maintainer:\|^MD5sum:\|^Source:\|^Breaks:\|^Multi-Arch:\|^Description-\|^Tag:\|^SHA256:"|awk '!NF{print line; line=""}{line=line " " $0}' |grep "Package: fonts-"|grep "fonts-$2"|head -1)
+		# p=$(unxz -c "${PACKAGES}" | grep -v "^Architecture:\|^Section:\|^Priority:\|^Replaces:\|^Provides:\|^Brekas:\|^Maintainer:\|^MD5sum:\|^Source:\|^Breaks:\|^Multi-Arch:\|^Description-\|^Tag:\|^SHA256:"|awk '!NF{print line; line=""}{line=line " " $0}' |grep "Package: fonts-"|grep "fonts-$2"|head -1)
+		p="$(unxz -c "${PACKAGES}" | awk '/^Package: fonts-'"$2"'/ {gsub(/^Package: /,"");print;exit;}')"
 		# Package: fonts-agave Version: 37-1 Installed-Size: 364 Description: monospaces programming font Homepage: https://b.agaric.net/page/agave Filename: pool/main/f/fonts-agave/fonts-agave_37-1_all.deb Size: 103112
 
-        	if [ -z "$p" ]; then
-		    q=$(curl -s "$GINDEX/ofl/" |grep "a href" |sed 's,.*">,google-,;s,/.*,,' |grep "$2" | head -1)
-		    s=$(curl -s "$GINDEX/apache/" |grep "a href" |sed 's,.*">,google-,;s,/.*,,' |grep "$2" | head -1)
+		if [ -z "$p" ]; then
+			q=$(curl -s "$GINDEX/ofl/" |grep "a href" |sed 's,.*">,google-,;s,/.*,,' |grep "$2" | head -1)
+			s=$(curl -s "$GINDEX/apache/" |grep "a href" |sed 's,.*">,google-,;s,/.*,,' |grep "$2" | head -1)
 
-		    if [ -z "$q" ] && [ -z "$s" ]; then
-        		echo "Font \"$2\" not found"
-        		exit 1
-		    else
-			echo "Installing google-${2}"
-			# here comes the google web font installer part using grep '\..tf'
-			curl -s "$GINDEX/ofl/${2}/" |grep "a href" |grep "\..tf" |sed 's,.*tf.>,,' | sed 's,</..*,,' | while read f; do
-			    curl -g -s "${GINDEX}/ofl/${2}/$f" -o "$target/$f"
-			done
-			curl -s "$GINDEX/apache/${2}/" |grep "a href" |grep "\..tf" |sed 's,.*tf.>,,' | sed 's,</..*,,' | while read f; do
-			    curl -g -s "${GINDEX}/apache/${2}/$f" -o "$target/$f"
+			if [ -z "$q" ] && [ -z "$s" ]; then
+				echo "Font \"$2\" not found"
+				exit 1
+			else
+				echo "Installing google-${2}"
+				# here comes the google web font installer part using grep '\..tf'
+				curl -s "$GINDEX/ofl/${2}/" |grep "a href" |grep "\..tf" |sed 's,.*tf.>,,' | sed 's,</..*,,' | while read -r f; do
+					curl -g -s "${GINDEX}/ofl/${2}/$f" -o "$target/$f"
+				done
+			curl -s "$GINDEX/apache/${2}/" |grep "a href" |grep "\..tf" |sed 's,.*tf.>,,' | sed 's,</..*,,' | while read -r f; do
+				curl -g -s "${GINDEX}/apache/${2}/$f" -o "$target/$f"
 			done
 			exit 0
-		    fi
-	        fi
+			fi
+		fi
 
-		name=$(echo "$p" | awk '{print $2}')
-		ver=$(echo "$p" | awk '{print $4}')
-		instsize=$(echo "$p" | awk '{print $6}')
-		downsize=$(echo "$p" | awk '{print $NF}')
-		url=$(echo "$p" | awk '{print $(NF-2)}')
-		f=$(basename "$url")
-		echo "Installing ${name} ${ver} [${downsize} ${instsize}000 ${MIRROR}/${url}]..."
-		curl -s "${MIRROR}/${url}" -o "${TMPDIR}/$f"
+		# get package infos
+		name="$p"
+		infos="$(unxz -c "${PACKAGES}" | awk "/^Package: ${name}/,/^$/" |awk '/^(Version|Installed-Size|Description|Filename|Size): /')"
+		ver=$(echo "$infos" | awk '/^Version: /{print$2}')
+		instsize=$(echo "$infos" | awk '/^Installed-Size: /{print$2}')
+		downsize=$(echo "$infos" | awk '/^Size: /{print$2}')
+		fpath=$(echo "$infos" | awk '/^Filename: /{print$2}')
+		f="$(basename "$fpath")"
+		echo "Installing ${name} ${ver} [${downsize} ${instsize}000 ${MIRROR}/${fpath}]..."
+		curl -s "${MIRROR}/${fpath}" -o "${TMPDIR}/$f"
 		cd "${TMPDIR}" || exit 1
 		data="$(ar t "$f" | grep data)"
 		ar x "$f" "$data"
 		tar xJf "$data"
-		find "${TMPDIR}" . -name "*.?tf" -exec cp {} "$target" \;
+		find "${TMPDIR}" -name "*.?tf" -exec cp {} "$target" \;
 		rm "$f" "$data"
 		rm -rf "${TMPDIR:?}/usr"
 	;;
@@ -176,8 +187,8 @@ case "$1" in
 		echo "Feel free to send patches or dollars (see the sponsor link)"
 	;;
 	search|-s)
-		if [ -f "$HOME/.fnt/Packages.xz" ]; then
-			unxz -c "$HOME/.fnt/Packages.xz" |grep ^Package:\ fonts-|awk '{print $2}' | grep "$2"
+		if [ -f "${PACKAGES}" ]; then
+			unxz -c "${PACKAGES}" |grep ^Package:\ fonts-|awk '{print $2}' | grep "$2"
 		fi
 		curl -s "$GINDEX/ofl/" |grep "a href" |sed 's,.*">,google-,;s,/.*,,' |grep -v "\.\.$" |grep "$2"
 		curl -s "$GINDEX/apache/" |grep "a href" |sed 's,.*">,google-,;s,/.*,,' |grep -v "\.\.$" |grep "$2"
