DreckOS

diff --git a/fnt b/fnt
--- a/fnt
+++ b/fnt
@@ -3,7 +3,7 @@
 set -e
 #set -u
 #set -o pipefail
-#set -x
+set -x
 
 # APT but only for fonts
 # alex@aiei.ch
@@ -19,6 +19,7 @@ MIRROR="https://deb.debian.org/debian"
 INDEX="${MIRROR}/dists/sid/main/binary-all/Packages.xz"
 # google fonts index
 GINDEX="http://bananas.debian.net/debian/google-fonts/fonts-main"
+mkdir -p "$FNTDATA/index" || { echo "Couldn't create index directory: $FNTDATA/index" ; exit 1 ; }
 
 if ! command -v uname &>/dev/null; then
 	s="Windows"
@@ -95,19 +96,17 @@ deb_handler() {
 	test -z "$(download "${MIRROR}/${FPATH}" "${TMPDIR}/$FNAME")" || { echo "Couldn't retrieve file." ; exit 1 ; }
 	echo "${MD5SUM}" > "${TMPDIR}/${FNAME}.md5"
 	if ${md5} -c "${TMPDIR}/${FNAME}.md5" >/dev/null; then
+		# deb data
 		DATA="$(ar t "$TMPDIR/$FNAME" | grep '^data\.tar')"
-		mkdir -p "${PIT}/data"
-		ar x --output "${PIT}" "${TMPDIR}/$FNAME" "$DATA"
-		cd "${PIT}/data" || { echo "Couldn't munch any tartar in: ${PIT}/control" ; exit 1 ; }
-		tar fx "${PIT}/$DATA"
+		mkdir -p "${PIT}/data" && cd "${PIT}/data"
+		ar x "${TMPDIR}/$FNAME" "$DATA"
+		tar xf "${PIT}/data/$DATA"
 		find "${PIT}/data" -name "*.?tf" -exec cp {} "$TARGET" \;
-		# extract filelist with md5sum
+		# deb control
 		CONTROL="$(ar t "$TMPDIR/$FNAME" | grep '^control\.tar')"
-		mkdir -p "${PIT}/control"
-		ar x --output "${PIT}" "${TMPDIR}/$FNAME" "$CONTROL"
-		cd "${PIT}/control" || { echo "Couldn't munch any tartar in: ${PIT}/control" ; exit 1 ; }
-		tar xf "${PIT}/$CONTROL"
-		mkdir -p "$FNTDATA/index" || { echo "Couldn't create index directory: $FNTDATA/index" ; exit 1 ; }
+		mkdir -p "${PIT}/control" && cd "${PIT}/control"
+		ar x "${TMPDIR}/$FNAME" "$CONTROL"
+		tar xf "${PIT}/control/$CONTROL"
 		sed -n 's/^\(.*\) .*\/\(.*tf$\)/\1 \2/p' "${PIT}/control/md5sums" > "$FNTDATA/index/$NAME"
 	else
 		echo "Can't verify md5sum!"
